-- All create table scripts at one place
use sys;

create table USERS(
	USER_ID 			INT NOT NULL,
    NAME				VARCHAR(50),
	USERNAME			VARCHAR(25),
	PASSWORD_ENC		VARCHAR(25),
	SECURITY_QUESTION	VARCHAR(100),			
	SECURITY_ANSWER_ENC	VARCHAR(25),
    CREATED_USER_ID		INT NOT NULL,
	CREATED_DATE	  	DATE NOT NULL,
	UPDATED_USER_ID		INT NOT NULL,
	UPDATED_DATE	  	DATE NOT NULL,
    CONSTRAINT USER_ID_PK PRIMARY KEY (USER_ID)
);

commit;

create table EXPENSES(
	EXPENSE_ID 			INT NOT NULL,
    DATE		  		DATE NOT NULL,
	DETAILS				VARCHAR(50),
	AMOUNT				INT,
	MODE				VARCHAR(25),
	CATEGORY			VARCHAR(25),			
	CREATED_USER_ID		INT NOT NULL,
	CREATED_DATE	  	DATE NOT NULL,
	UPDATED_USER_ID		INT NOT NULL,
	UPDATED_DATE	  	DATE NOT NULL,
    CONSTRAINT EXPENSE_ID_PK PRIMARY KEY (EXPENSE_ID),
    CONSTRAINT CREATED_USER_ID_FK FOREIGN KEY (CREATED_USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT UPDATED_USER_ID_FK FOREIGN KEY (UPDATED_USER_ID) REFERENCES USERS(USER_ID)
);
commit;
